services:
  data-scraper:
    container_name: data-scraper-container
    build:
      context: .
      dockerfile: Dockerfile
    image: aesbube/data-scraper:latest
    restart: no
    ports:
      - "3000:3000" 
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/app   
    command: ["Scraper"] 